// reporting-system/frontend/src/components/DataTable.tsx
import { useMemo, useState } from 'react';
import { useReactTable, getCoreRowModel, flexRender } from '@tanstack/react-table';
import type { ColumnDef, SortingState } from '@tanstack/react-table';
import { useReportStore } from '../store';

type Doc = Record<string, unknown>;

export default function DataTable() {
  const { docs, total, start, rows, setStart, setRows, visibleColumns, fields, sort, setSort, loading } = useReportStore();
  const [sorting, setSorting] = useState<SortingState>([]);

  const columns = useMemo<ColumnDef<Doc>[]>(() => {
    const cols = visibleColumns.length > 0
      ? fields.filter((f) => visibleColumns.includes(f.name))
      : fields;

    return cols.map((f) => ({
      accessorKey: f.name,
      header: () => (
        <span
          style={{ cursor: 'pointer', userSelect: 'none' }}
          onClick={() => {
            const isAsc = sort === `${f.name} asc`;
            setSort(isAsc ? `${f.name} desc` : `${f.name} asc`);
          }}
        >
          {f.label}
          {sort.startsWith(f.name) ? (sort.endsWith('asc') ? ' ▲' : ' ▼') : ''}
        </span>
      ),
      cell: (info) => {
        const val = info.getValue();
        if (val === null || val === undefined) return <span style={{ color: '#a0aec0' }}>—</span>;
        return String(val);
      },
    }));
  }, [visibleColumns, fields, sort]);

  const table = useReactTable({
    data: docs,
    columns,
    getCoreRowModel: getCoreRowModel(),
    manualSorting: true,
    state: { sorting },
    onSortingChange: setSorting,
  });

  const totalPages = Math.ceil(total / rows);
  const currentPage = Math.floor(start / rows) + 1;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      {/* Pagination & Stats Row */}
      <div style={{ 
        display: 'flex', 
        alignItems: 'center', 
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: 16,
        padding: '12px 16px',
        background: '#f8fafc',
        borderRadius: 12,
        border: '1px solid #e2e8f0'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
          <span style={{ fontSize: 13, fontWeight: 600, color: '#475569' }}>
            {total.toLocaleString()} <span style={{ fontWeight: 400, color: '#64748b' }}>total records</span>
          </span>
          <span style={{ fontSize: 13, fontWeight: 600, color: '#475569' }}>
            Page {currentPage} <span style={{ fontWeight: 400, color: '#64748b' }}>of {totalPages || 1}</span>
          </span>
          <button
            onClick={() => {
              const { filters } = useReportStore.getState();
              import('../api').then(({ exportData }) => {
                exportData(filters.rules.length > 0 ? filters : undefined);
              });
            }}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              padding: '6px 12px',
              borderRadius: 8,
              border: '1px solid #e2e8f0',
              background: '#fff',
              color: '#475569',
              fontSize: 12,
              fontWeight: 600,
              cursor: 'pointer',
              marginLeft: 8,
              boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
              transition: 'all 0.2s'
            }}
          >
            <span style={{ fontSize: 14 }}>📥</span>
            Export CSV
          </button>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginRight: 12 }}>
            <span style={{ fontSize: 13, color: '#64748b' }}>Show</span>
            <select 
              value={rows} 
              onChange={(e) => { setRows(Number(e.target.value)); setStart(0); }} 
              style={{ 
                padding: '4px 8px', 
                borderRadius: 8, 
                border: '1px solid #e2e8f0', 
                fontSize: 13,
                fontWeight: 600,
                outline: 'none',
                background: '#fff'
              }}
            >
              {[25, 50, 100, 200, 500].map((n) => (<option key={n} value={n}>{n} / page</option>))}
            </select>
          </div>

          <div style={{ display: 'flex', gap: 4 }}>
            {[
              { label: '«', action: () => setStart(0), disabled: start === 0 },
              { label: '‹ Prev', action: () => setStart(Math.max(0, start - rows)), disabled: start === 0 },
              { label: 'Next ›', action: () => setStart(start + rows), disabled: start + rows >= total },
              { label: '»', action: () => setStart((totalPages - 1) * rows), disabled: start + rows >= total },
            ].map((btn, idx) => (
              <button
                key={idx}
                disabled={btn.disabled}
                onClick={btn.action}
                style={{
                  padding: '6px 12px',
                  borderRadius: 8,
                  border: '1px solid #e2e8f0',
                  cursor: btn.disabled ? 'not-allowed' : 'pointer',
                  background: btn.disabled ? '#f1f5f9' : '#fff',
                  color: btn.disabled ? '#cbd5e1' : '#475569',
                  fontSize: 12,
                  fontWeight: 600,
                  transition: 'all 0.2s'
                }}
              >
                {btn.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {loading ? (
        <div style={{ textAlign: 'center', padding: 40, fontSize: 16, color: '#888' }}>Loading...</div>
      ) : (
        <div style={{ overflowX: 'auto', borderRadius: 8, border: '1px solid #e2e8f0' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
            <thead>
              {table.getHeaderGroups().map((hg) => (
                <tr key={hg.id} style={{ background: '#f7fafc' }}>
                  {hg.headers.map((header) => (
                    <th key={header.id} style={{ padding: '10px 12px', textAlign: 'left', borderBottom: '2px solid #e2e8f0', fontWeight: 700, whiteSpace: 'nowrap', color: '#2d3748' }}>
                      {flexRender(header.column.columnDef.header, header.getContext())}
                    </th>
                  ))}
                </tr>
              ))}
            </thead>
            <tbody>
              {table.getRowModel().rows.length === 0 ? (
                <tr><td colSpan={columns.length || 1} style={{ textAlign: 'center', padding: 32, color: '#a0aec0' }}>No data found</td></tr>
              ) : (
                table.getRowModel().rows.map((row, i) => (
                  <tr key={row.id} style={{ background: i % 2 === 0 ? '#fff' : '#f7fafc' }}>
                    {row.getVisibleCells().map((cell) => (
                      <td key={cell.id} style={{ padding: '8px 12px', borderBottom: '1px solid #e2e8f0', whiteSpace: 'nowrap', maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis' }}>
                        {flexRender(cell.column.columnDef.cell, cell.getContext())}
                      </td>
                    ))}
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// reporting-system/frontend/src/components/DataTable.vue
<template>
  <div class="data-table-wrapper">
    <!-- Column Selector bar -->
    <div class="table-toolbar">
      <div class="col-selector">
        <div class="dropdown" ref="colDropdown">
          <button class="btn-dropdown" @click="showColDropdown = !showColDropdown">
            📊 Columns ({{ store.selectedColumns.length }}) ▾
          </button>
          <div class="dropdown-menu" v-if="showColDropdown">
            <div class="dropdown-search">
              <input type="text" v-model="colSearch" placeholder="Filter columns..." />
            </div>
            <div class="dropdown-items">
              <label 
                class="dropdown-item" 
                v-for="f in filteredFields" 
                :key="f.name"
              >
                <input 
                  type="checkbox" 
                  :value="f.name" 
                  v-model="store.selectedColumns"
                />
                {{ f.label }}
              </label>
            </div>
          </div>
        </div>
      </div>
      <div class="table-actions">
        <button class="btn-search" @click="reload" :disabled="store.loading">
          {{ store.loading ? '...' : '🔍 Search' }}
        </button>
        <span class="count-badge">{{ store.total.toLocaleString() }} rows</span>
        <select v-model.number="store.rows" class="rows-select" @change="reload">
          <option :value="25">25 / page</option>
          <option :value="50">50 / page</option>
          <option :value="100">100 / page</option>
        </select>
        <button class="btn-export" @click="store.exportCsv()">⬇ Export CSV</button>
      </div>
    </div>

    <!-- Loading / Error states -->
    <div class="table-state" v-if="store.loading">
      <div class="spinner"></div> Loading data…
    </div>
    <div class="table-state error" v-else-if="store.error">⚠ {{ store.error }}</div>

    <!-- Table -->
    <div class="table-scroll" v-else>
      <table class="report-table">
        <thead>
          <tr>
            <th
              v-for="(col, index) in store.selectedColumns"
              :key="col"
              :draggable="true"
              @dragstart="startDragCol($event, index)"
              @dragover.prevent="onDragOverCol($event, index)"
              @drop="dropCol($event, index)"
              @click="setSort(col)"
              :style="{ minWidth: (store.columnWidths[col] ?? 140) + 'px' }"
              :class="{ 'th-sortable': true, 'drag-over': dragOverIdx === index }"
            >
              <div class="th-inner">
                <span>{{ labelFor(col) }}</span>
                <span class="sort-icon" v-if="sortField === col">
                  {{ sortDir === 'asc' ? '▲' : '▼' }}
                </span>
                <span class="sort-icon muted" v-else>⇅</span>
              </div>
              <!-- Resize handle -->
              <div
                class="resize-handle"
                @mousedown.stop="startResize($event, col)"
              ></div>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-if="store.docs.length === 0">
            <td :colspan="store.selectedColumns.length" class="empty-row">
              No records found.
            </td>
          </tr>
          <tr
            v-else
            v-for="(doc, i) in store.docs"
            :key="i"
            :class="{ 'row-alt': i % 2 === 1 }"
          >
            <td v-for="col in store.selectedColumns" :key="col">
              {{ formatCell(doc[col]) }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Pagination -->
    <div class="pagination" v-if="!store.loading && store.total > 0">
      <button class="page-btn" :disabled="store.start === 0" @click="store.setPage(0)">«</button>
      <button class="page-btn" :disabled="store.start === 0" @click="store.setPage(Math.max(0, store.start - store.rows))">‹</button>
      <span class="page-info">
        {{ store.start + 1 }}–{{ Math.min(store.start + store.rows, store.total) }} of {{ store.total.toLocaleString() }}
      </span>
      <button class="page-btn" :disabled="store.start + store.rows >= store.total" @click="store.setPage(store.start + store.rows)">›</button>
      <button class="page-btn" :disabled="store.start + store.rows >= store.total" @click="store.setPage(Math.floor(store.total / store.rows) * store.rows)">»</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, onMounted, onUnmounted } from 'vue'
import { useReportStore } from '../stores/reportStore'

const store = useReportStore()
const colDropdown = ref<HTMLElement | null>(null)
const showColDropdown = ref(false)
const colSearch = ref('')

const filteredFields = computed(() => {
  if (!colSearch.value) return store.fields
  const s = colSearch.value.toLowerCase()
  return store.fields.filter(f => f.label.toLowerCase().includes(s))
})

// Close dropdown on outside click
function handleClickOutside(e: MouseEvent) {
  if (colDropdown.value && !colDropdown.value.contains(e.target as Node)) {
    showColDropdown.value = false
  }
}

onMounted(() => window.addEventListener('click', handleClickOutside))
onUnmounted(() => window.removeEventListener('click', handleClickOutside))

const sortField = ref('')
const sortDir   = ref<'asc' | 'desc'>('asc')

function reload() {
  store.start = 0
  store.fetchData()
}

function labelFor(col: string) {
  return store.fields.find(f => f.name === col)?.label ?? col
}

function formatCell(val: any): string {
  if (val === undefined || val === null) return '—'
  if (Array.isArray(val)) return val.join(', ')
  return String(val)
}

function setSort(col: string) {
  if (sortField.value === col) {
    sortDir.value = sortDir.value === 'asc' ? 'desc' : 'asc'
  } else {
    sortField.value = col
    sortDir.value = 'asc'
  }
  store.sort = `${col} ${sortDir.value}`
  store.start = 0
  store.fetchData()
}

// --- Column resize ---
let resizeStartX = 0
let resizeCol = ''
let resizeStartW = 0

function startResize(e: MouseEvent, col: string) {
  e.preventDefault()
  e.stopPropagation()
  resizeCol    = col
  resizeStartX = e.clientX
  resizeStartW = store.columnWidths[col] ?? 140

  const onMove = (ev: MouseEvent) => {
    const diff = ev.clientX - resizeStartX
    store.setColWidth(resizeCol, Math.max(80, resizeStartW + diff))
  }
  const onUp = () => {
    window.removeEventListener('mousemove', onMove)
    window.removeEventListener('mouseup', onUp)
  }
  window.addEventListener('mousemove', onMove)
  window.addEventListener('mouseup', onUp)
}

// --- Column Reordering (Drag & Drop) ---
const draggedIdx = ref<number | null>(null)
const dragOverIdx = ref<number | null>(null)

function startDragCol(e: DragEvent, index: number) {
  draggedIdx.value = index
  if (e.dataTransfer) {
    e.dataTransfer.effectAllowed = 'move'
    e.dataTransfer.dropEffect = 'move'
  }
}

function onDragOverCol(_e: DragEvent, index: number) {
  dragOverIdx.value = index
}

function dropCol(_e: DragEvent, index: number) {
  if (draggedIdx.value === null || draggedIdx.value === index) {
    dragOverIdx.value = null
    return
  }
  
  const cols = [...store.selectedColumns]
  const [removed] = cols.splice(draggedIdx.value, 1)
  cols.splice(index, 0, removed)
  
  store.selectedColumns = cols
  draggedIdx.value = null
  dragOverIdx.value = null
}
</script>

<style scoped>
.data-table-wrapper {
  background: white;
  border-radius: 0.75rem;
  border: 1px solid #e5e7eb;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

/* toolbar */
.table-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  padding: 1rem 1.5rem;
  border-bottom: 1px solid #f3f4f6;
  flex-wrap: wrap;
  gap: 1rem;
}

.dropdown { position: relative; }
.btn-dropdown {
  background: white;
  border: 1px solid #d1d5db;
  padding: 0.4rem 0.85rem;
  border-radius: 0.375rem;
  font-size: 0.8rem;
  font-weight: 600;
  color: #374151;
  transition: all 0.15s;
}
.btn-dropdown:hover { border-color: #6366f1; color: #4f46e5; }

.dropdown-menu {
  position: absolute;
  top: 100%;
  left: 0;
  margin-top: 0.5rem;
  background: white;
  border: 1px solid #e5e7eb;
  border-radius: 0.5rem;
  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
  z-index: 100;
  min-width: 240px;
  max-height: 400px;
  display: flex;
  flex-direction: column;
}

.dropdown-search {
  padding: 0.75rem;
  border-bottom: 1px solid #f3f4f6;
}
.dropdown-search input {
  width: 100%;
  padding: 0.35rem 0.65rem;
  border: 1px solid #d1d5db;
  border-radius: 0.375rem;
  font-size: 0.75rem;
  outline: none;
}
.dropdown-search input:focus { border-color: #6366f1; }

.dropdown-items {
  overflow-y: auto;
  padding: 0.5rem;
}

.dropdown-item {
  display: flex;
  align-items: center;
  gap: 0.65rem;
  padding: 0.45rem 0.75rem;
  border-radius: 0.375rem;
  font-size: 0.8rem;
  color: #374151;
  cursor: pointer;
}
.dropdown-item:hover { background: #f9fafb; }
.dropdown-item input { width: 14px; height: 14px; cursor: pointer; }

.table-actions {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.count-badge {
  font-size: 0.75rem;
  color: #6b7280;
  white-space: nowrap;
}

.rows-select {
  padding: 0.35rem 0.6rem;
  border-radius: 0.375rem;
  border: 1px solid #d1d5db;
  font-size: 0.8rem;
  color: #374151;
  background: #f9fafb;
  outline: none;
}

.btn-export {
  background: #f9fafb;
  border: 1px solid #d1d5db;
  color: #374151;
  font-size: 0.8rem;
  font-weight: 600;
  padding: 0.35rem 0.85rem;
  border-radius: 0.375rem;
  transition: all 0.15s;
}
.btn-export:hover { border-color: #6366f1; color: #4f46e5; }

.btn-search {
  background: #f97316;
  border: 1px solid #ea580c;
  color: white;
  font-size: 0.85rem;
  font-weight: 700;
  padding: 0.45rem 1.25rem;
  border-radius: 0.375rem;
  transition: all 0.15s;
  box-shadow: 0 1px 2px rgba(249, 115, 22, 0.2);
}
.btn-search:hover:not(:disabled) { background: #ea580c; transform: translateY(-1px); box-shadow: 0 4px 6px rgba(249, 115, 22, 0.25); }
.btn-search:active { transform: translateY(0); }
.btn-search:disabled { opacity: 0.6; cursor: not-allowed; }

/* states */
.table-state {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 3rem;
  color: #6b7280;
  font-size: 0.9rem;
  gap: 0.75rem;
}
.table-state.error { color: #ef4444; }

.spinner {
  width: 20px;
  height: 20px;
  border: 2px solid #e5e7eb;
  border-top-color: #6366f1;
  border-radius: 50%;
  animation: spin 0.7s linear infinite;
}
@keyframes spin { to { transform: rotate(360deg); } }

/* table */
.table-scroll {
  overflow-x: auto;
  overflow-y: auto;
  max-height: 480px;
}

.report-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.8125rem;
}

.report-table thead th {
  position: sticky;
  top: 0;
  background: #f8fafc;
  z-index: 1;
  text-align: left;
  font-weight: 600;
  font-size: 0.75rem;
  color: #374151;
  text-transform: uppercase;
  letter-spacing: 0.03em;
  padding: 0.75rem 1rem;
  border-bottom: 1px solid #e5e7eb;
  white-space: nowrap;
  cursor: pointer;
  user-select: none;
  position: relative;
}

.th-inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.5rem;
}

.sort-icon { font-size: 0.7rem; color: #6366f1; }
.sort-icon.muted { color: #d1d5db; }

.th-sortable:hover .sort-icon.muted { color: #9ca3af; }

.th-sortable[draggable="true"] {
  cursor: grab;
}
.th-sortable[draggable="true"]:active {
  cursor: grabbing;
}
.th-sortable.drag-over {
  border-left: 2px solid #6366f1 !important;
  background: #f0f4ff !important;
}

.resize-handle {
  position: absolute;
  right: 0;
  top: 0;
  width: 5px;
  height: 100%;
  cursor: col-resize;
  z-index: 2;
}
.resize-handle:hover { background: rgba(99, 102, 241, 0.25); }

.report-table tbody td {
  padding: 0.65rem 1rem;
  border-bottom: 1px solid #f3f4f6;
  color: #374151;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 280px;
}

.row-alt td { background: #fafafa; }

.report-table tbody tr:hover td {
  background: #f0f4ff;
}

.empty-row {
  text-align: center;
  padding: 3rem!important;
  color: #9ca3af;
}

/* pagination */
.pagination {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 0.5rem;
  padding: 0.75rem 1.5rem;
  border-top: 1px solid #f3f4f6;
}

.page-btn {
  width: 32px;
  height: 32px;
  border-radius: 0.375rem;
  border: 1px solid #e5e7eb;
  background: white;
  font-size: 0.875rem;
  color: #374151;
  transition: all 0.15s;
}
.page-btn:hover:not(:disabled) { border-color: #6366f1; color: #4f46e5; }
.page-btn:disabled { opacity: 0.35; cursor: not-allowed; }

.page-info {
  font-size: 0.8rem;
  color: #6b7280;
  padding: 0 0.5rem;
  white-space: nowrap;
}
</style>
